### ISSUE TITLE
macOS Big Sur not open

### ISSUE THREAD

**Issue by hilham1990** [j4nf4b3l/MagicClock#4]
the program does not open, can you tell me which systems should be used Thanks in advance

**Comment by j4nf4b3l** [comment]
Make sure to turn off SIP and try to run again. This should pretty much fix your issue...

**Comment by hilham1990** [comment]
Thanks a lot it's fixed

Jan Fabel ***@***.***>, 14 Ağu 2022 Paz, 15:02 tarihinde şunu
yazdı:

**Comment by hilham1990** [comment]
I did as you said it worked thanks
What is the license price for MagicClock. Do we have iCloud bypass service
for phone?. Congratulations on your success

Huseynov Ilham ***@***.***>, 14 Ağu 2022 Paz, 16:53 tarihinde
şunu yazdı:
